namespace Shinobytes.XzaarScript.Ast
{
    public enum TokenType
    {
        Identifier,
        Number,
        String,
                
        Minus,
        MinusEquals,
        MinusMinus,
        MinusGreater,
        Plus,
        PlusPlus,
        PlusEquals,
        Multiply,
        MultiplyEquals,
        Divide,
        DivideEquals,
        DivideDivide,
        Modulus,
        ModulusEquals,
        Equals,
        EqualsEquals,
        EqualsGreater,
        Greater,
        GreaterEquals,
        GreaterGreater,
        GreaterGreaterEquals,
        Less,
        LessEquals,
        LessLess,
        LessLessEquals,
        And,
        AndEquals,
        AndAnd,
        Or,
        OrEquals,
        OrOr,

        Not,
        NotEquals,

        QuestionMark,
        QuestionMarkQuestionMark,

        Semicolon,
        Colon,
        ColonColon,
        Comma,
        Dot,
        LeftParan,
        RightParan,
        LeftCurly,
        RightCurly,
        LeftBracket,
        RightBracket,
    }
}